# Generated by Django 3.1.7 on 2021-03-10 15:17

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbladvtbsc',
            fields=[
                ('advtno'       , models.IntegerField(default=0, primary_key=True)),                # 광고번호
                ('advttpcd'     , models.CharField(max_length=30)),                                 # 광고종류코드
                ('advttitl'     , models.CharField(max_length=200)),                                # 광고제목
                ('advtstadate'  , models.CharField(max_length=8)),                                  # 광고시작일자
                ('advtenddate'  , models.CharField(max_length=8)),                                  # 광고종료일자
                ('advtdesc'     , models.CharField(max_length=3000)),                               # 광고내용
                ('advtgrdcd'    , models.CharField(max_length=30)),                                 # 광고등급코드
                ('delyn'        , models.CharField(max_length=1)),                                  # 삭제여부
                ('fstaddtmst'   , models.CharField(max_length=30)),                                 # 최초등록일시
                ('fstaddid'     , models.DecimalField(decimal_places=2, default=0, max_digits=10)), # 최초등록ID
                ('lastupttmst'  , models.DateTimeField(default=datetime.now(), blank=True)),        # 최종변경일시   
                ('lastuptid'    , models.CharField(max_length=30)),
            ],

        ),
    ]