# Generated by Django 3.2.5 on 2021-07-24 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiLooker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Tbladvtbsc',
            options={'ordering': ['-advtno']},
        ),
        migrations.AlterField(
            model_name='Tbladvtbsc',
            name='fstaddid',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='Tbladvtbsc',
            name='fstaddtmst',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 24, 15, 10, 23, 773822)),
        ),
        migrations.AlterField(
            model_name='Tbladvtbsc',
            name='lastupttmst',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 24, 15, 10, 23, 773822)),
        ),
    ]
