# Generated by Django 3.2.5 on 2021-07-25 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiLooker_app', '0002_auto_20210724_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Tbladvtbsc',
            name='fstaddtmst',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 25, 13, 27, 25, 823337)),
        ),
        migrations.AlterField(
            model_name='Tbladvtbsc',
            name='lastupttmst',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 25, 13, 27, 25, 823337)),
        ),
    ]
